controllers/ComentarioController.php
<?php

namespace app\controllers;
header('Access-Control-Allow-Origin: *');            
use Yii;
use app\models\Comentario;
use app\models\ComentarioSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;

/**
 * ComentarioController implements the CRUD actions for Comentario model.
 */
class ComentarioController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
[
            'class' => \yii\behaviors\TimestampBehavior::className(),
            'createdAtAttribute' => 'at_created',
            'updatedAtAttribute' => 'at_updated',
            'value' => new \yii\db\Expression('NOW()'),
        ],
        ];
    }

    /**
     * Lists all Comentario models.
     * @return mixed
     */
    public function actionIndex()
    {
        $searchModel = new ComentarioSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);
        $comentarios = Comentario::find()->all();
        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'comentarios' => $comentarios,

        ]);
    }

    public function actionTodosweb()
    {   
        $arr = "";  
        $comentarios = Comentario::find()->orderBy(['id'=>SORT_DESC])->all();
        $arr = $arr.'<div class="container"> 
                <div class="testimonials-slider"> 
                    <div class="slides-pagin"></div>
                    <ul class="t-slides center" >  ';
        foreach ($comentarios as $comentario ){
        $arr = $arr.'<li class="monial animated" data-animation="fadeInUp" data-animation-delay="400"><h3 class="monial-title uppercase white">'.$comentario->comentario.'</h3><img src="http://localhost:8080/coment/'. $comentario->foto .'" alt="'.$comentario->autor.'"><p class="author italic">'.$comentario->autor.'</p></li>';  

        }
        $arr = $arr.'</ul>
                </div>
            </div>';
       ////////////// return json_encode(array('data'=>$arr));
        return    $arr  ;
    }

    public function actionTodos()
    {
        $comentarios = Comentario::find()->orderBy(['id'=>SORT_DESC])->all();
        $cant = Comentario::find()->count();
        $dif = $cant - $_GET["cant"];

        $arr = "";
$i = 0;
        foreach ($comentarios as $comentario ) 
        {
            if ($comentario->estado == "0") {
                $cad2 = '<h6><span class="label label-danger">No Publicado</span></h6>'; 
                $cad3 = ' <li>'. \yii\helpers\Html::a('Publicar', ['publicar', 'id' => $comentario->id], [ ]).'</li> '; 
            }else{
                $cad2 = '<h6><span class="label label-success">Publicado</span></h6>'; 
                $cad3 = ' <li>'. \yii\helpers\Html::a('Despublicar', ['despublicar', 'id' => $comentario->id], [ ]).'</li> ';
            }


            $i++;
            if ($dif > 0 && $_GET["cant"] != "-1") {
                $cad = 'class="success"';
                $dif--;
            }else{
                $cad = '';
            }
           
            $arr = $arr. '<tr '.$cad.'>
                        <td>
                            <aside class="contentHeight">
                                <span>'.$comentario->autor.'</span> </aside>
                                                        </td><td><aside class="contentHeight">
                                                                <span>'. $comentario->empresa.'</span>
                                                                                            </aside>
                                                                                        </td>
                                                                                        <td>
                                                                                            <aside class="contentHeight">
                                                                                                <span>'
                        .$comentario->comentario .'</span>
                                                    </aside>
                                                </td>
                                                <td class="text-center" style="width:10%;">
                                                    <img   src="coment/'. $comentario->foto .'" width="100" alt="" class="img-circle">
                                                                            </td>                      
                                <td class="text-center" style="width:10%;">'.$cad2.'</td> 
                                                                            <td style="width:10%;">
                                                                                <aside class="contentHeight text-uppercase">
                                                                                    <div class="btn-group">
                                                                                        <button type="button" class="btn btn-default dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                                                                        Acciones <span class="caret"></span>
                                                                                        </button>
                                                                                        <ul class="dropdown-menu "> 


  '.$cad3.'
 
 <li>'. \yii\helpers\Html::a('Ver', ['view', 'id' => $comentario->id], [ ]).'</li> 
 <li>'. \yii\helpers\Html::a('Editar', ['update', 'id' => $comentario->id], [ ]).'</li> 
<li>'.\yii\helpers\Html::a('Borrar', ['delete', 'id' => $comentario->id], [
            'class' => '',
            'data' => [
                'confirm' => 'Desea borrar este item?',
                'method' => 'post',
            ],
        ]).'</li>                                        
                                     </ul>
                                 </div>
                             </aside>
                          </td>                      
                     </tr>';

        }
        return json_encode(array('data'=>$arr, 'cant'=>$i));
    }

    /**
     * Displays a single Comentario model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Comentario model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
    public function actionCreate()
    {
        $model = new Comentario();

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            if($_FILES["Comentario"]["error"]["foto"] == "0" )
            {
                $model->foto = \yii\web\UploadedFile::getInstance($model, 'foto');            
                $model->foto->saveAs('coment/' . $model->id.'.'.$model->foto->extension);
                $model->foto = $model->id.'.'.$model->foto->extension;
                $model->save();               
            }        
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('create', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Updates an existing Comentario model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
    public function actionPublicar($id)
    {
        $model = $this->findModel($id);
        $model->estado = 1; 
        $model->save();
        return $this->redirect(['index']);
    }

    public function actionDespublicar($id)
    {
        $model = $this->findModel($id);
        $model->estado = 0; 
        $model->save();
        return $this->redirect(['index']);
    }

    public function actionUpdate($id)
    {
        $model = $this->findModel($id);

        if ($model->load(Yii::$app->request->post()) && $model->save()) {

            if($_FILES["Comentario"]["error"]["foto"] == "0" )
            {
                @unlink('coment/' . $model->id.'.'.$model->foto->extension);
                $model->foto = \yii\web\UploadedFile::getInstance($model, 'foto');            
                $model->foto->saveAs('coment/' . $model->id.'.'.$model->foto->extension);
                $model->foto = $model->id.'.'.$model->foto->extension;
                $model->save();               
            }  
            return $this->redirect(['view', 'id' => $model->id]);
        } else {
            return $this->render('update', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Deletes an existing Comentario model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
    public function actionDelete($id)
    {
        $model = $this->findModel($id);
        $model->delete();
        @unlink('coment/' . $model->id.'.'.$model->foto->extension);
        $model->delete();
        return $this->redirect(['index']);
    }

    /**
     * Finds the Comentario model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Comentario the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Comentario::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }

views/layouts/main.php
<?php

/* @var $this \yii\web\View */
/* @var $content string */

use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <?php if (
    (Yii::$app->controller->action->id == 'login' && Yii::$app->controller->id == 'site')
        || 
    (Yii::$app->controller->action->id == 'recovery' && Yii::$app->controller->id == 'site') 
        || 
    (Yii::$app->controller->action->id == 'getpass' && Yii::$app->controller->id == 'site')   
    ) { ?>
    <style>body{padding-top:40px;padding-bottom:40px;background-color:#eee}.form-signin{max-width:330px;padding:15px;margin:0 auto}.form-signin .checkbox,.form-signin .form-signin-heading{margin-bottom:10px}.form-signin .checkbox{font-weight:400}.form-signin .form-control{position:relative;height:auto;-webkit-box-sizing:border-box;-moz-box-sizing:border-box;box-sizing:border-box;padding:10px;font-size:16px}.form-signin .form-control:focus{z-index:2}.form-signin input[type=email]{margin-bottom:-1px;border-bottom-right-radius:0;border-bottom-left-radius:0}.form-signin input[type=password]{margin-bottom:10px;border-top-left-radius:0;border-top-right-radius:0}</style>
    <?php $out = "0"; }else{ $out = "1";} ?>
</head>
<body>
<?php $this->beginBody() ?>

<div class="wrap">
    <?php
     if ($out == "1" ) {
        NavBar::begin([
            'brandLabel' => 'Dashboard',
            'brandUrl' => ['/comentario'],
            'options' => [
                'class' => 'navbar-default navbar-fixed-top',
            ],
        ]);
        echo Nav::widget([
            'options' => ['class' => 'navbar-nav navbar-right'],
            'items' => [
                ['label' => 'Crear comentario', 'url' => ['/comentario/create']],
                Yii::$app->params['guest']  ? (
                    ['label' => 'Login', 'url' => ['/site/login']]
                ) : (
                    '<li>'
                    . Html::beginForm(['/site/logout'], 'post')
                    . Html::submitButton(
                        'Logout ',
                        ['class' => 'btn btn-link logout']
                    )
                    . Html::endForm()
                    . '</li>'
                )
            ],
        ]);
        NavBar::end();
    }
    ?>

    <div class="container">
<?php if ($out == "1" ) { ?>
        <?= Breadcrumbs::widget([
            'homeLink' => ['label' => 'Home','url' => 'index.php?r=comentario/index'],
            'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
        ]) ?>
        <?php } ?>
        <?= $content ?>
    </div>
</div>

<?php if ($out == "1" ) { ?>
<footer class="footer">
    <div class="container">
        <p class="pull-left">&copy; My Company <?= date('Y') ?></p>

        <p class="pull-right"><?= Yii::powered() ?></p>
    </div>
</footer>
<?php } ?>
<?php $this->endBody();   ?>
</body>
<script src="/assets/js/datatables.min.js"></script>
<script>
            $(document).ready(function() {                          
                    $('#listadoGeneral').DataTable( {
                        language: {
                            "sProcessing":     "Procesando...",
                            "sLengthMenu":     "Mostrar _MENU_ registros",
                            "sZeroRecords":    "No se encontraron resultados",
                            "sEmptyTable":     "Ningún dato disponible en esta tabla",
                            "sInfo":           "Mostrando registros del _START_ al _END_ de un total de _TOTAL_ registros",
                            "sInfoEmpty":      "Mostrando registros del 0 al 0 de un total de 0 registros",
                            "sInfoFiltered":   "(filtrado de un total de _MAX_ registros)",
                            "sInfoPostFix":    "",
                            "sSearch":         "Buscar:",
                            "sUrl":            "",
                            "sInfoThousands":  ",",
                            "sLoadingRecords": "Cargando...",
                            "oPaginate": {
                                "sFirst":    "Primero",
                                "sLast":     "Último",
                                "sNext":     "Siguiente",
                                "sPrevious": "Anterior"
                            },
                            "oAria": {
                                "sSortAscending":  ": Activar para ordenar la columna de manera ascendente",
                                "sSortDescending": ": Activar para ordenar la columna de manera descendente"
                            }
                        }
                } );

            
            } );
            var cant = -1;
            setInterval(function(){ 
                $.ajax({
                    method: "GET",
                    url: "http://localhost:8080/index.php?r=comentario/todos",
                    data:{cant:cant} ,
                    success:function(data){
                        var json = $.parseJSON(data);
                        if(cant == json['cant'])
                        {

                        }else{
                            $("#in").html(json['data']); 
                            cant = json['cant'];
                        }
                     
                    }   
                });
            }, 1000);
                      

        </script>
</html>
<?php $this->endPage() ?>